const medm = [
    'Anarin',
    'Baduila',
    'Bill Ferny',
    'Dâsakûn',
    'Deallus',
    'Drór',
    'Elerína',
    'Elwen',
    'Eun',
    'Firiel',
    'Fori the Beardless',
    'Gergeli',
    'Gisulf',
    'Golodhros',
    'The Grimburgoth',
    'Herion',
    'Ivic',
    'Jûoma',
    'Leamon',
    'Nimloth',
    'Ôm-buri-Ôm',
    'Pôn-ora-Pôn',
    'Râisha',
    'Súrion',
    'Taladhan',
    'Woffung',
    'Wormtongue',
    'Lobelia Sackville-Baggins',
    'My Precious',
    'The Gem-deeps',
    'Haudh-in-Gwanur',
    'Hermit\'s Hill',
    'The Iron-deeps',
    'The Pûkel-deeps',
    'The Sulfur-deeps',
    'The Under-courts',
    'The Under-galleries',
    'The Under-gates',
    'The Under-grottos',
    'The Under-leas',
    'The Under-vaults',
    'Urlurtsu Nurn',
    'An Article Missing',
    'Angmar Arises',
    'An Unexpected Outpost',
    'Aware of their Ways',
    'The Black Enemy\'s Wrath',
    'Bring Our Curses Home',
    'Chance of Being Lost',
    'Cunning Foes',
    'Doubled Vigilance',
    'Drums',
    'Earth-tremors',
    'Endless Whispers',
    'Exhalation of Decay',
    'Eyes of the Shadow',
    'Faces of the Dead',
    'Flies and Spiders',
    'Foes Shall Fall',
    'Gnaw with Words',
    'Good Sense Revolts',
    'Great Need or Purpose',
    'Great Secrets Buried There',
    'Helms of Iron',
    'In Darkness Bind Them',
    'In Great Wrath',
    'In the Heart of his Realm',
    'Inner Cunning',
    'Like the Crash of Battering-rams',
    'Long Dark Reach',
    'The Moon Is Dead',
    'Mordor in Arms',
    'Neither so Ancient Nor so Potent',
    'Never Seen Him',
    'No Way Forward',
    'Nobody\'s Friend',
    'Out of the Black Sky',
    'Pale Dream-maker',
    'Pierced by Many Wounds',
    'Rank upon Rank',
    'Reaching Shadow',
    'The Reach of Ulmo',
    'Redoubled Force',
    'Reluctant Final Parting',
    'Revealed to all Watchers',
    'Scimitars of Steel',
    'Seek without Success',
    'Seized by Terror',
    'Shadow out of the Dark',
    'Spells of the Barrow-wights',
    'Sudden Fury',
    'To Get You Away',
    'Tribal Banner',
    'Tribal Totem',
    'Troll-purse',
    'Twisted Tales',
    'Two or Three Tribes Present',
    'The Way is Shut',
    'Waylaid, Wounded, and Orc-dragged',
    'Which Might Be Lies',
    'Will not Come Down',
    'Wound of Long Burden',
    'Wraith-lord',
    'Your Welcome Is Doubtful',
    'Bûthrakaur the Green',
    'Chill Douser',
    'Durin\'s Bane',
    'Little Snuffler',
    'Nameless Thing',
    'Spider of the Môrlat',
    'Stirring Bones',
    'Umagaur the Pale',
    'Wisp of Pale Sheen',
    'An Unexpected Party',
    'Ancient Stair',
    'Armory',
    'Await the Advent of Allies',
    'Balance Between Powers',
    'Barrow-blade',
    'Choice of Lúthien',
    'Crown of Flowers',
    'Cup of Farewell',
    'Dark Numbers',
    'The Dwarves Are upon You!',
    'Enduring Tales',
    'Eyes of Mandos',
    'Face out of Sight',
    'Fate of the Ithil-stone',
    'Fifteen Birds in Five Firtrees',
    'Fireworks',
    'First of the Order',
    'Forwarned Is Forarmed',
    'Free to Choose',
    'Hall of Fire',
    'Healing of Nimrodel',
    'Herb-lore',
    'Here Is a Snake!',
    'Hidden Knife',
    'Hobbit-lore',
    'Horns, Horns, Horns',
    'Hour of Need',
    'Hundreds of Butterflies',
    'The Hunt',
    'I Know Much about You',
    'Into Dark Tunnels',
    'Into the Smoking Cone',
    'Knowledge of the Enemy',
    'Mallorn',
    'Memories Recalled',
    'More Alert than Most',
    'No Waiting to Wonder',
    'Ordered to Kill',
    'Palm to Palm',
    'Pass the Doors of Dol Guldur',
    'Rebuild the Town',
    'Saw Further and Deeper',
    'Secret Ways',
    'Sentinels of Numenor',
    'Smoke Rings',
    'Token of Goodwill',
    'To the Uttermost Foundations',
    'Vein of Arda',
    'When You Know More',
    'The Windlord Found Me',
    'Withdrawn to Mordor',
    'Aiglos',
    'Dragon-helm',
    'Dwarven Light-stone',
    'Forgotten Scrolls',
    'Gems of Arda',
    'Leaf Brooch',
    'Lost Tome',
    'Mithril',
    'Necklace of Girion',
    'Noldo-lantern',
    'Phial of Galadriel',
    'Lindion the Oronin',
    'Mistress Lobelia',
    'Noble Hound',
    'Folco Boffin',

    'Forewarned is Forearmed'
]
