const metd = [
    'Brand',
    'Fram Framson',
    'Galdor',
    'Ioreth',
    'Thráin II',
    'Adamant Helmet',
    'Arrows Shorn of Ebony',
    'Bow of Dragon-horn',
    'Cram',
    'Emerald of Doriath',
    'Emerald of the Mariner',
    'Enruned Shield',
    'Gold Belt of Lórien',
    'Habergeon of Silver',
    'Magical Harp',
    'Necklace of Silver and Pearls',
    'Scabbard of Chalcedony',
    'Thrór\'s Map',
    'Twice-baked Cakes',
    'Valiant Sword',
    'Waybread',
    'Wizards\'s Staff',
    'Wormsbane',
    'A Short Rest',
    'Alert the Folk',
    'And Forth He Hastened',
    'Belegaer',
    'Bounty of the Hoard',
    'Burglary',
    'Cloudless Day',
    'Dragon\'s Hunger',
    'Dragon-feuds',
    'Dragon-lore',
    'Dwarven Hoard',
    'Echo of All Joy',
    'Elf-path',
    'Fast Asleep',
    'Flatter a Foe',
    'Forod',
    'Gift of Comprehension',
    'Harad',
    'Helm of Her Secrecy',
    'Here, There, or Yonder',
    'Hey! come merry dol!',
    'Houses of Healing',
    'King under the Mountain',
    'Legendary Hoard',
    'Look More Closely Later',
    'Lore of the Ages',
    'Many Foes He Fought',
    'Many Turns and Doublings',
    'Map to Mithril',
    'Marvels Told',
    'Master of Esgaroth',
    'Master of Wood, Water, or Hill',
    'Mathom Lore',
    'More Sense Than You',
    'Not at Home',
    'Pledge of Conduct',
    'Refuge',
    'Rhûn',
    'Riddling Talk',
    'Sated Beast',
    'Secret News',
    'Skin-changer',
    'Staff Asunder',
    'Star of High Hope',
    'Tales of the Hunt',
    'The Riddle Game',
    'Three Golden Hairs',
    'Trickery',
    'Vanish in Sunlight!',
    'Warm Now Be Heart and Limb',
    'Washed and Refreshed',
    'When I Know Anything',
    'Wielded Twice',
    'Wit',
    'Wizard Uncloaked',
    'Wondrous Maps',
    'Men of Dale',
    'Men of Lake-town',
    'Returned Exiles',
    'Nenseldë the Wingild',
    'Bairanax',
    'Carrion Birds',
    'Cave Worm',
    'Dire Wolves',
    'Dunlending Raiders',
    'Eärcaraxë',
    'Gothmog',
    'Hobgoblins',
    'Ice-drake',
    'Itangast',
    'Land-drake',
    'Lesser Spiders',
    'Light-drake',
    'Marsh-drake',
    'Morgul-rats',
    'Rain-drake',
    'Sand-drake',
    'Scatha',
    'Scorba',
    'Sea Serpent',
    'Thunder\'s Companion',
    'True Cold-drake',
    'True Fire-drake',
    'Were-worm',
    'Wild Fell Beast',
    'Winged Cold-drake',
    'Winged Fire-drake',
    'Wolf-riders',
    'Agburanar Ahunt',
    'Agburanar at Home',
    'Bairanax Ahunt',
    'Bairanax at Home',
    'Black Breath',
    'Cruel Caradhras',
    'Daelomin Ahunt',
    'Daelomin at Home',
    'Deftness of Agility',
    'Dragon\'s Blood',
    'Dragon\'s Breath',
    'Dragon\'s Curse',
    'Dragon\'s Terror',
    'Dragon-sickness',
    'Eärcaraxë Ahunt',
    'Eärcaraxë at Home',
    'Exile of Solitude',
    'Fever of Unrest',
    'Foolish Words',
    'Frenzy of Madness',
    'From the Pits of Angband',
    'Half an Eye Open',
    'Host of Bats',
    'Icy Touch',
    'Incite Denizens',
    'Incite Minions',
    'Itangast Ahunt',
    'Itangast at Home',
    'Known to an Ounce',
    'Left Behind',
    'Leucaruth Ahunt',
    'Leucaruth at Home',
    'Many Sorrows Befall',
    'Memories Stolen',
    'No Escape from My Magic',
    'Noose of the Sea',
    'Parsimony of Seclusion',
    'Passion of Wrath',
    'Peril Returned',
    'Prowess of Age',
    'Prowess of Might',
    'Rumor of Wealth',
    'Scatha Ahunt',
    'Scatha at Home',
    'Scorba Ahunt',
    'Scorba at Home',
    'Searching Eye',
    'Shadow of Mordor',
    'Sleepless Malice',
    'Smaug Ahunt',
    'Smaug at Home',
    'Song of the Lady',
    'Stormcrow',
    'Subtlety of Guile',
    'Times Are Evil',
    'Velocity of Haste',
    'Winds of Wrath',
    'Withered Lands',
    'Worm\'s Stench',
    'Worn and Famished',
]
