var _4_lidlessEye = [
    'Adûnaphel the Ringwraith',
    'Akhôrahil the Ringwraith',
    'Dwar the Ringwraith',
    'Hoarmûrath the Ringwraith',
    'Indûr the Ringwraith',
    'Khamûl the Ringwraith',
    'Ren the Ringwraith',
    'Ûvatha the Ringwraith',
    'The Witch-king',
    'Asternak',
    'Belegorn',
    'Bróin',
    'Calendal',
    'Carambor',
    'Ciryaher',
    'Dôgrib',
    'Dorelas',
    'Dunlending Spy',
    'Eradan',
    'Gorbag',
    'Grishnákh',
    'Gulla',
    'Hador',
    'Hendolen',
    'Horseman in the Night',
    'Jerrek',
    'Lagduf',
    'Layos',
    'Lieutenant of Angmar',
    'Lieutenant of Morgul',
    'Lieutenant of Dol Guldur',
    'Luitprand',
    'The Mouth',
    'Muzgash',
    'Náin',
    'Nevido Smôd',
    'Odoacer',
    'Old Troll',
    'Orc Brawler',
    'Orc Captain',
    'Orc Chieftain',
    'Orc Sniffler',
    'Orc Tracker',
    'Orc Veteran',
    'Ostisen',
    'Pon Opar',
    'Radbug',
    'Shagrat',
    'Shámas',
    'Snaga',
    'Tarcil',
    'Threlin',
    'Troll Lout',
    'Troll-chief',
    'Tros Hesnef',
    'Uchel',
    'Ufthak',
    'Ulkaur the Tongueless',
    'A Little Gold Ring',
    'Binding-ring',
    'Black Mace',
    'Black-hide Shield',
    'Black-mail Coat',
    'Blazon of the Eye',
    'Bright Gold Ring',
    'Broad-headed Spear',
    'Dwarven Ring of Durin\'s Tribe',
    'Dwarven Ring of Dwálin\'s Tribe',
    'Dwarven Ring of Bávor\'s Tribe',
    'Dwarven Ring of Drúin\'s Tribe',
    'Dwarven Ring of Barin\'s Tribe',
    'Foul-smelling Paste',
    'Gleaming Gold Ring',
    'Gold Ring that Sauron Fancies',
    'High Helm',
    'The Iron Crown',
    'The Least of Gold Rings',
    'Magic Ring of Lies',
    'Magic Ring of Fury',
    'Magic Ring of Guile',
    'Magic Ring of Enigma',
    'Magic Ring of Savagery',
    'Magic Ring of Weals',
    'Magic Ring of Delusion',
    'Magic Ring of Shadows',
    'Minor Ring',
    'The Mithril-coat',
    'The One Ring',
    'The Oracle\'s Ring',
    'Orc-draughts',
    'Orc-liquor',
    'Palantír of Osgiliath',
    'Palantír of Amon Sûl',
    'Palantír of Elostirion',
    'Palantír of Annúminas',
    'Palantír of Orthanc',
    'Palantír of Minas Tirith',
    'Paltry Ring',
    'Perfect Gold Ring',
    'Poison',
    'Red Book of Westmarch',
    'The Reviled Ring',
    'Sable Shield',
    'Saw-toothed Blade',
    'Scroll of Isildur',
    'Shadow-cloak',
    'Strange Rations',
    'Trifling Ring',
    'The Warding Ring',
    'Whip',
    'A Malady Without Healing',
    'A Nice Place to Hide',
    'Adûnaphel Unleashed',
    'Akhôrahil Unleashed',
    'All Thought Bent Upon It',
    'An Untimely Whisper',
    'Awaiting the Call',
    'Back to the Fray',
    'Bade to Rule',
    'Bitter Cold',
    'Black Rain',
    'Black Rider',
    'Blow Turned',
    'Bold Thrust',
    'Burning Rick, Cot, and Tree',
    'By the Ringwraith\'s Word',
    'Catch an Elusive Scent',
    'Come By Night Upon Them',
    'Crack in the Wall',
    'Crooked Promptings',
    'Deeper Shadow',
    'Diversion',
    'Down Down to Goblin-town',
    'Dwar Unleashed',
    'Fell Rider',
    'Focus Palantír',
    'Forced March',
    'Foul Trophies',
    'Freeze the Flesh',
    'Gifts as Given of Old',
    'Gold Chains in the Wind',
    'Heralded Lord',
    'Hidden Ways',
    'Hide in Dark Places',
    'Hoarmûrath Unleashed',
    'Honey on the Tongue',
    'I\'ll Be At Your Heels',
    'I\'ll Report You',
    'In the Name of Mordor',
    'Indûr Unleashed',
    'Iron Road',
    'Khamûl Unleashed',
    'Kill All But NOT the Halflings',
    'Leg It Double Quick',
    'The Lidless Eye',
    'Messenger of Mordor',
    'Morgul-blade',
    'Motionless Among the Slain',
    'The Names Among Them',
    'News Must Get Through',
    'News of the Shire',
    'No More Nonsense',
    'No News of Our Riding',
    'Not Slay Needlessly',
    'Old Cache',
    'Old Prejudice',
    'One Dear to You',
    'Orc Quarrels',
    'Orc Stealth',
    'Orc-mounts',
    'Poisonous Despair',
    'Ready to His Will',
    'Remnants of Old Robberies',
    'Ren Unleashed',
    'The Ring Leaves Its Mark',
    'Rumor of the One',
    'Ruse',
    'Secrets of Their Forging',
    'Seize Prisoners',
    'Skies of Fire',
    'Smart and Secret',
    'Smoke on the Wind',
    'Sneakin',
    'Some Secret Art of Flame',
    'Spying out the Land',
    'Stabbed Him in His Sleep',
    'Sudden Call',
    'Swag',
    'Swarm of Bats',
    'Swift Strokes',
    'Test of Fire',
    'That Ain\'t No Secret',
    'That\'s Been Heard Before Tonight',
    'They Ride Together',
    'Thing Stolen',
    'Threats',
    'Tiding of Death',
    'To Satisfy the Questioner',
    'Under his Blow',
    'Ûvatha Unleashed',
    'Veils of Shadow',
    'Voices of Malice',
    'The Water\'s Tithe',
    'We Have Come to Kill',
    'Weigh All Things to a Nicety',
    'Where There\'s a Whip',
    'While the Yellow Face Sleeps',
    'Wisdom to Wield',
    'The Witch-king Unleashed',
    'Words of Menace and Deceit',
    'Agburanar Roused',
    'Balchoth',
    'Beornings',
    'Black Trolls',
    'Dunlendings',
    'Easterlings',
    'Goblins of Goblin-gate',
    'Grey Mountain Goblins',
    'Half-trolls',
    'Hill Trolls',
    'Hillmen',
    'Ice-orcs',
    'Men of Dorwinion',
    'Misty Mountain Wargs',
    'Nûrniags',
    'Orcs of the Red Eye',
    'Orcs of the Ephel Dúath',
    'Orcs of Angmar',
    'Orcs of Moria',
    'Orcs of Gorgoroth',
    'Orcs of Mirkwood',
    'Orcs of Gundabad',
    'Orcs of the Ash Mountains',
    'Orcs of Udûn',
    'Scatha Roused',
    'Scorba Roused',
    'Smaug Roused',
    'Snaga-hai',
    'Southrons',
    'Stone Trolls',
    'Umbarean Corsairs',
    'Ungol-Orcs',
    'Uruk-hai',
    'Variags of Khand',
    'Wargs of the Forochel',
    'White Mountain Wolves',
    'Woodmen',
    'Woses of the Eryn Vorn',
    'Blackbole',
    'Last Child of Ungoliant',
    'Stinker',
    '"Two-headed" Troll',
    'The Warg-king',
    'War-warg',
    'War-wolf',
    'Ambusher',
    'Arthadan Rangers',
    'Barrow-wight',
    'Beorning Toll',
    'The Border-watch',
    'Brigands',
    'Cave Worm',
    'Cave-drake',
    'Corpse-candle',
    'Dire Wolves',
    'Elf-lord Revealed in Wrath',
    'Elves Upon Errantry',
    'Ent in Search of the Entwives',
    'Ghosts',
    'Ghouls',
    'Giant',
    'Giant Spiders',
    'Gondorian Rangers',
    'Hobgoblins',
    'Horse-lords',
    'Huorn',
    'Land-drake',
    'Landroval',
    'Lawless Men',
    'Lesser Spiders',
    'Marsh-drake',
    'Orc-raiders',
    'Orc-warband',
    'Orc-watch',
    'Pirates',
    'Sellswords Between Charters',
    'Slayer',
    'Sons of Kings',
    'Stirring Bones',
    'Thranduil\'s Folk',
    'Thunder\'s Companion',
    'True Fire-drake',
    'Uruk-lieutenant',
    'Wandering Eldar',
    'Wargs',
    'Watcher in the Water',
    'Wild Trolls',
    'Arouse Defenders',
    'Arouse Denizens',
    'Awaken Defenders',
    'Awaken Denizens',
    'Call of Home',
    'Chill Them with Fear',
    'Covetous Thoughts',
    'Darkness under Tree',
    'Despair of the Heart',
    'Doors of Night',
    'Fell Winter',
    'Foolish Words',
    'Greed',
    'Heedless Revelry',
    'Incite Defenders',
    'Incite Denizens',
    'Long Winter',
    'Lost in Border-lands',
    'Lost in Free-domains',
    'Lost in Wilderness',
    'Lost in Shadow-lands',
    'Lure of Expedience',
    'Lure of Nature',
    'Lure of the Senses',
    'Minions Stir',
    'Muster Disperses',
    'News of Doom',
    'Nothing to Eat or Drink',
    'Plague',
    'Plague of Wights',
    'Rats!',
    'Rebel-talk',
    'The Ring Will Have But One Master',
    'River',
    'The Roving Eye',
    'Searching Eye',
    'Shut Yer Mouth',
    'So You\'ve Come Back',
    'Something Has Slipped',
    'Stay Her Appetite',
    'Stench of Mordor',
    'Thrice Outnumbered',
    'Tidings of Bold Spies',
    'Tidings of Doubt and Danger',
    'Twilight',
    'Veils Flung Away',
    'Waiting Shadow',
    'Wake of War',
    'Weariness of the Heart',
    'Webs of Fear and Treachery',
    'Wrath of the West',
    'Amon Hen',
    'Bag End',
    'Bandit Lair',
    'Barad-dûr',
    'Barrow-downs',
    'Beorn\'s House',
    'Blue Mountain Dwarf-hold',
    'Bree',
    'Buhr Widu',
    'Cameth Brin',
    'Carn Dûm',
    'Caves of Ûlund',
    'Cirith Gorgor',
    'Cirith Ungol',
    'Dale',
    'Dead Marshes',
    'Dimrill Dale',
    'Dol Amroth',
    'Dol Guldur',
    'Drúadan Forest',
    'Dunharrow',
    'Dunnish Clan-hold',
    'Easterling Camp',
    'Edoras',
    'Ettenmoors',
    'Geann a-Lisch',
    'Gladden Fields',
    'Glittering Caves',
    'Gobel Mírlond',
    'Goblin-gate',
    'Gondmaeglom',
    'Haudh-in-Gwanûr',
    'Henneth Annûn',
    'Hermit\'s Hill',
    'Iron Hill Dwarf-hold',
    'Isengard',
    'Lake-town',
    'Lond Galen',
    'The Lonely Mountain',
    'Lossadan Cairn',
    'Lossadan Camp',
    'Minas Morgul',
    'Minas Tirith',
    'Moria',
    'Mount Doom',
    'Mount Gram',
    'Mount Gundabad',
    'Nûrniag Camp',
    'Ost-in-Edhil',
    'Pelargir',
    'Raider-hold',
    'Ruined Signal Tower',
    'Sarn Gorwing',
    'Shelob\'s Lair',
    'Shrel-Kain',
    'Southron Oasis',
    'Stone-circle',
    'The Stones',
    'Tharbad',
    'Thranduil\'s Halls',
    'Urlurtsu Nurn',
    'Vale of Erech',
    'Variag Camp',
    'The White Towers',
    'The Wind Throne',
    'Woodmen-town',
    'The Worthy Hills',
    'Wose Passage-hold',
    'Zarak Dûm',
];
