var _7_theBalrog = [
    'Strider',
    'Azog',
    'Bolg',
    'Bûthrakaur',
    'Crook-legged Orc',
    'Hill-troll',
    'Mountain-maggot',
    'The Balrog',
    'Umagaur',
    'Crept Along Carefully',
    'Elven Rope',
    'Longbottom Leaf',
    'Rumours of Rings',
    'Show Things Unbidden',
    'To Fealty Sworn',
    'Stabbing Tongue of Fire',
    'Whip of Many Tongues',
    'A More Evil Hour',
    'Ancient Secrets',
    'Angband Revisited',
    'Breach the Hold',
    'Caverns Unchoked',
    'Challenge the Power',
    'Cloaked by Darkness',
    'Crowned with Storm',
    'Darkness Wielded',
    'Descent through Fire',
    'Eddy in Fate’s Tide',
    'Flame of Udûn',
    'Foe Dismayed',
    'Gangways over the Fire',
    'Going Ever Under Dark',
    'Great Army of the North',
    'Great Fissure',
    'Great Shadow',
    'Grond',
    'Heart of Dark Fire',
    'Invade Their Domain',
    'Long Grievous Siege',
    'Lord and Usurper',
    'Maker\'s Map',
    'Memories of Old Torture',
    'Mine or No One\'s',
    'No Better Use',
    'Obey Him or Die',
    'Orders from the Great Demon',
    'Out He Sprang',
    'People Diminished',
    'Prone to Violence',
    'Roam the Waste',
    'Roots of the Earth',
    'Sauron',
    'Scourge of Fire',
    'Strangling Coils',
    'Tempest of Fire',
    'Terror Heralds Doom',
    'Vanguard of Might',
    'Whispers of Rings',
    'A Few Recruits',
    'Cave Troll',
    'Evil Things Lingering',
    'Great Troll',
    'Nasty Slimy Thing',
    'Beorning Skin-changers',
    'Carrion Feeders',
    'Monstrosity of Diverse Shape',
    'Olog Warlords',
    'Shelob’s Brood',
    'Spawn of Ungoliant',
    'Ungoliant\'s Foul Issue',
    'Ungoliant\'s Progeny',
    'Black Vapour',
    'Darkness Made by Malice',
    'Desire All for Thy Belly',
    'Diminish and Depart',
    'Fled into Darkness',
    'Glance of Arien',
    'Imprisoned and Mocked',
    'Press Gang',
    'The Reek',
    'The Sun Shone Fiercely',
    'Unabated in Malice',
    'Ancient Deep-hold',
    'Barad-dûr',
    'Carn Dûm',
    'Cirith Gorgor',
    'Cirith Ungol',
    'Dol Guldur',
    'Minas Morgul',
    'Moria',
    'Remains of Thangorodrim',
    'The Drowning-deeps',
    'The Gem-deeps',
    'The Iron-deeps',
    'The Pûkel-deeps',
    'The Rusted-deeps',
    'The Sulfur-deeps',
    'The Under-courts',
    'The Under-galleries',
    'The Under-gates',
    'The Under-grottos',
    'The Under-leas',
    'The Under-vaults',
    'The Wind-deeps',
];
