const meas = [
    'Bûrat',
    'Mauhúr',
    'Mîonid',
    'Perchen',
    'Tûma',
    'Wûluag',
    'Bow of the Galadhrim',
    'The Ithil-stone',
    'Jewel of Beleriand',
    'Ancient Black Axe',
    'Dwarven Ring of Thélor\'s Tribe',
    'Dwarven Ring of Thrár\'s Tribe',
    'Goblin Earth-plumb',
    'Helm of Fear',
    'Iron Shield of Old',
    'Necklace of Girion',
    'Old Treasure',
    'Records Unread',
    'Secret Book',
    'Thong of Fire',
    'Thrall-ring',
    'Thrór\'s Map',
    'Troth-ring',
    'Usriev of Treachery',
    'All the Bells Ringing',
    'Alliance of Free Peoples',
    'Biter and Beater!',
    'Drughu',
    'Farmer Maggot',
    'Glamour of Surpassing Excellance',
    'Mount Slain',
    'No Strangers at this Time',
    'Orc-mail',
    'Power Against the Shadow',
    'Safe from the Shadow',
    'Spies Feared',
    'The Sun Unveiled',
    'Tower Raided',
    'Above the Abyss',
    'The Ash Mountain Deeps',
    'The Dark Power',
    'Dark Tryst',
    'Driven as by a Madness',
    'Eye Never Sleeping',
    'Faithless Steward',
    'Far Below the Deepest Delvings',
    'The Great Eye',
    'Hail of Darts',
    'Hoard Well-searched',
    'Hold Rebuilt and Repaired',
    'Hounds of Sauron',
    'Join With That Power',
    'Legendary Stair',
    'The Misty Mountain Deeps',
    'The Mountains of Shadow Deeps',
    'Orders from Lugbúrz',
    'Our Own Wolves',
    'Padding Feet',
    'Powers Too Dark and Terrible',
    'Riven Gate',
    'Sack Over the Head',
    'Steeds',
    'Tokens to Show',
    'The Tormented Earth',
    'Treason the Greatest Foe',
    'Tribute Garnered',
    'The Undeeps of Anduin',
    'The Under-roads',
    'Use Your Legs',
    'Well-preserved',
    'The White Mountain Cavern-ways',
    'World Gnawed by the Nameless',
    'Angmarim',
    'Haradrim',
    'Nûrniags',
    'Petty-dwarves',
    'Wain-easterlings',
    'Woses of the Eryn Vorn',
    'Angmarim',
    'Asdriags',
    'Bairanax Roused',
    'Black Númenóreans',
    'Corsairs of Rhûn',
    'Daelomin Roused',
    'Eärcaraxë Roused',
    'Haradrim',
    'Itangast Roused',
    'Leucaruth Roused',
    'Morgul-orcs',
    'Nûriags',
    'Orcs of Dol Guldur',
    'Petty-dwarves',
    'Wain-easterlings',
    'The Balrog',
    'Black Horse',
    'Creature of and Older World',
    'Great Bats',
    'Great Lord of Goblin-gate',
    'Regiment of Black Crows',
    'Alatar the Hunter',
    'Durin\'s Folk',
    'Dwarven Travelers',
    'Galadhrim',
    'Gandalf the White Rider',
    'Knights of the Prince',
    'Lady of the Golden Wood',
    'Lord of the Carrock',
    'Lord of the Haven',
    'Master of the House',
    'Pallando the Soul-keeper',
    'Radagast the Tamer',
    'Saruman the Wise',
    'Steward\'s Guard',
    'Stout Men of Gondor',
    'Trolls from the Mountains',
    'A Lie in Your Eyes',
    'Alone and Unadvised',
    'Come at Need',
    'Early Harvest',
    'Enchanted Stream',
    'Fealty Under Trial',
    'FEAR! FIRE! FOES!',
    'Full of Froth and Rage',
    'Near to Hear a Whisper',
    'One Foe to Breed a War',
    'Pilfer Anything Unwatched',
    'Power Built by Waiting',
    'Returned Beyond All Hope',
    'Ride Against the Enemy',
    'Short Legs Are Slow',
    'Slip Treacherously',
    'Summons from Long Sleep',
    'Trouble on All Borders',
    'Turning Hope to Despair',
    'Unhappy Blows',
    'Will Shaken',
    'Cirith Gorgor',
    'Geann a-Lisch',
    'Gobel Mírlond',
    'Nûrniag Camp',
    'Raider-hold',
    'The Worthy Hills',
    'Dancing Spire',
    'Eagles\' Eyrie',
    'Edhellond',
    'Framsburg',
    'The Gem-deeps',
    'Gold Hill',
    'Grey Havens',
    'Himring',
    'Irerock',
    'The Iron-deeps',
    'Isle of the Ulond',
    'Isles of the Dead that Live',
    'Lórien',
    'Old Forest',
    'Ovir Hollow',
    'The Pûkel-deeps',
    'Rhosgobel',
    'Rivendell',
    'The Sulfur-deeps',
    'Tolfalas',
    'The Under-courts',
    'The Under-galleries',
    'The Under-gates',
    'The Under-grottos',
    'The Under-leas',
    'The Under-vaults',
    'Weathertop',
    'Wellinghall',
]
