const metw = [
    'Adrazar',
    'Alatar',
    'Anborn',
    'Annalena',
    'Aragorn II',
    'Arinmîr',
    'Arwen',
    'Balin',
    'Bard Bowman',
    'Barliman Butterbur',
    'Beorn',
    'Beregond',
    'Beretar',
    'Bergil',
    'Bifur',
    'Bilbo',
    'Bofur',
    'Bombur',
    'Boromir II',
    'Celeborn',
    'Cirdan',
    'Dain II',
    'Damrod',
    'Denethor II',
    'Dori',
    'Dwalin',
    'Elladan',
    'Elrohir',
    'Elrond',
    'Éomer',
    'Éowyn',
    'Erkenbrand',
    'Faramir',
    'Fili',
    'Forlong',
    'Frodo',
    'Galadriel',
    'Galva',
    'Gamling the Old',
    'Gandalf',
    'Ghan-buri-Ghan',
    'Gildor Inglorion',
    'Gimli',
    'Glóin',
    'Glorfindel II',
    'Halbarad',
    'Haldalam',
    'Haldir',
    'Háma',
    'Imrahil',
    'Kíli',
    'Legolas',
    'Mablung',
    'Merry',
    'Nori',
    'Óin',
    'Ori',
    'Orophin',
    'Pallando',
    'Peath',
    'Pippin',
    'Radagast',
    'Robin Smallburrow',
    'Sam Gamgee',
    'Saruman',
    'Théoden',
    'Thorin II',
    'Thranduil',
    'Vôteli',
    'Vygavril',
    'Wacho',
    'A Chance Meeting',
    'A Friend or Three',
    'Align Palantír',
    'Anduin River',
    'Anduril',
    'Army of the Dead',
    'Ash Mountains',
    'Athelas',
    'Beautiful Gold Ring',
    'Beornings',
    'Bill the Pony',
    'Block',
    'Blue Mountain Dwarves',
    'Book of Mazarbul',
    'Bridge',
    'Clear Skies',
    'Concealment',
    'Cracks of Doom',
    'Dagger of Westernesse',
    'Dark Quarrels',
    'Dodge',
    'Dreams of Lore',
    'Dunlendings',
    'Durin\'s Axe',
    'Dw. Ring of Barin\'s Tribe',
    'Dw. Ring of Bávor\'s Tribe',
    'Dw. Ring of Drúin\'s Tribe',
    'Dw. Ring of Durin\'s Tribe',
    'Dw. Ring of Dwálin\'s Tribe',
    'Dw. Ring of Thélor\'s Tribe',
    'Dw. Ring of Thrár\'s Tribe',
    'Eagle-mounts',
    'Earth of Galadriel\'s Orchard',
    'Easterlings',
    'Elf-song',
    'Elf-stone',
    'Elven Cloak',
    'Elves of Lindon',
    'Ent-draughts',
    'Ents of Fangorn',
    'Escape',
    'Fair Gold Ring',
    'Fair Sailing',
    'Fair Travels in Border-lands',
    'Fair Travels in Dark-domains',
    'Fair Travels in Free-domains',
    'Fair Travels in Shadow-lands',
    'Fair Travels in Wilderness',
    'Far-sight',
    'Favor of the Valar',
    'Fellowship',
    'Fog',
    'Ford',
    'Gates of Morning',
    'Glamdring',
    'Goldberry',
    'Gollum',
    'Gollum\'s Fate',
    'Great Ship',
    'Great-road',
    'Great-shield of Rohan',
    'Gwaihir',
    'Halfling Stealth',
    'Halfling Strength',
    'Hauberk of Bright Mail',
    'Healing Herbs',
    'Hiding',
    'Hillmen',
    'Hobbits',
    'Horn of Anor',
    'Horses',
    'Iron Hill Dwarves',
    'Kindling of the Spirit',
    'Knights of Dol Amroth',
    'Lapse of Will',
    'Leaflock',
    'Lesser Ring',
    'Lordly Presence',
    'Lossoth',
    'Lucky Search',
    'Lucky Strike',
    'Magic Ring of Courage',
    'Magic Ring of Lore',
    'Magic Ring of Nature',
    'Magic Ring of Stealth',
    'Magic Ring of Words',
    'Men of Anfalas',
    'Men of Anórien',
    'Men of Dorwinion',
    'Men of Lamedon',
    'Men of Lebennin',
    'Men of Northern Rhovanion',
    'Mirror of Galadriel',
    'Miruvor',
    'Misty Mountains',
    'Moon',
    'Morannon',
    'Mountains of Shadow',
    'Muster',
    'Narsil',
    'Narya',
    'Nenya',
    'New Friendship',
    'Old Friendship',
    'Old Road',
    'Orcrist',
    'Palantír of Amon Sûl',
    'Palantír of Annuminas',
    'Palantír of Elostirion',
    'Palantír of Minas Tirith',
    'Palantír of Orthanc',
    'Palantír of Osgiliath',
    'Paths of the Dead',
    'Persuasive Words',
    'Potion of Prowess',
    'Praise to Elbereth',
    'Precious Gold Ring',
    'Quickbeam',
    'Quiet Lands',
    'Rangers of Ithilien',
    'Rangers of the North',
    'Red Arrow',
    'Red Book of Westmarch',
    'Reforging',
    'Rescue Prisoners',
    'Return of the King',
    'Riders of Rohan',
    'Ringlore',
    'Risky Blow',
    'Roäc the Raven',
    'Sacrifice of Form',
    'Sapling of the White Tree',
    'Scroll of Isildur',
    'Secret Entrance',
    'Secret Passage',
    'Shadowfax',
    'Shield of Iron-bound Ash',
    'Skinbark',
    'Southrons',
    'Star-glass',
    'Stars',
    'Stealth',
    'Sting',
    'Stone of Erech',
    'Sun',
    'Sword of Gondolin',
    'Tempering Friendship',
    'Test of Form',
    'Test of Lore',
    'The Arkenstone',
    'The Cock Crows',
    'The Evenstar',
    'The Great Eagles',
    'The Mithril-coat',
    'The Old Thrush',
    'The One Ring',
    'The White Tree',
    'Thorough Search',
    'Tom Bombadil',
    'Torque of Hues',
    'Tower Guard of Minas Tirith',
    'Treebeard',
    'True Fána',
    'Use Palantír',
    'Vanishment',
    'Variags of Khand',
    'Vilya',
    'White Mountains',
    'Wizard\'s Fire',
    'Wizard\'s Flame',
    'Wizard\'s Laughter',
    'Wizard\'s Ring',
    'Wizard\'s River-horses',
    'Wizard\'s Test',
    'Wizard\'s Voice',
    'Wood-elves',
    'Woodmen',
    'Woses of Old Pukel-land',
    'Woses of the Drúadan Forest',
    '"Bert" - Bûrat',
    '"Tom" - Tûma',
    '"William" - Wûluag',
    'Abductor',
    'Adûnaphel',
    'Agburanar',
    'Akhôrahil',
    'Ambusher',
    'Arouse Denizens',
    'Arouse Minions',
    'Assassin',
    'Awaken Denizens',
    'Awaken Minions',
    'Awaken the Earth\'s Fire',
    'Balrog of Moria',
    'Bane of the Ithil-stone',
    'Barrow-wight',
    'Brigands',
    'Call of Home',
    'Call of the Sea',
    'Cave-drake',
    'Choking Shadows',
    'Clouds',
    'Corpse-candle',
    'Corsairs of Umbar',
    'Crebain',
    'Daelomin',
    'Despair of the Heart',
    'Doors of Night',
    'Dragon\'s Desolation',
    'Drowning Seas',
    'Dwar of Waw',
    'Eye of Sauron',
    'Fell Beast',
    'Fell Turtle',
    'Fell Winter',
    'Foul Fumes',
    'Ghosts',
    'Ghouls',
    'Giant',
    'Giant Spiders',
    'Gloom',
    'Greed',
    'Half-trolls of Far Harad',
    'Hoarmûrath of Dír',
    'Huorn',
    'Indûr Dawndeath',
    'Khamûl the Easterling',
    'Leucaruth',
    'Long Winter',
    'Lost at Sea',
    'Lost in Border-lands',
    'Lost in Dark-domains',
    'Lost in Free-domains',
    'Lost in Shadow-lands',
    'Lost in the Wilderness',
    'Lure of Creation',
    'Lure of Expedience',
    'Lure of Nature',
    'Lure of Power',
    'Lure of the Senses',
    'Minions Stir',
    'Morgul Night',
    'Morgul-horse',
    'Morgul-knife',
    'Mouth of Sauron',
    'Mûmak (Oliphant)',
    'Muster Disperses',
    'New Moon',
    'Night',
    'Old Man Willow',
    'Olog-hai (Trolls)',
    'Orc-guard',
    'Orc-lieutenant',
    'Orc-patrol',
    'Orc-raiders',
    'Orc-warband',
    'Orc-warriors',
    'Orc-watch',
    'Pick-pocket',
    'Plague of Wights',
    'Pûkel-men',
    'Ren the Unclean',
    'River',
    'Rogrog',
    'Shelob',
    'Siege',
    'Silent Watcher',
    'Slayer',
    'Smaug',
    'Snowstorm',
    'Storms of Ossë',
    'The Balance of Things',
    'The Burden of Time',
    'The Great Goblin',
    'The Nazgul are Abroad',
    'The Pale Sword',
    'The Precious',
    'The Ring\'s Betrayal',
    'The Will of Sauron',
    'The Will of the Ring',
    'Thief',
    'Tookish Blood',
    'Traitor',
    'Twilight',
    'Uvatha the Horseman',
    'Wake of War',
    'Wargs',
    'Watcher in the Water',
    'Weariness of the Heart',
    'Witch-king of Angmar',
    'Wolves',
    'Words of Power and Terror',
    'Amon Hen',
    'Bag End',
    'Bandit Lair',
    'Barad-dur',
    'Barrow-downs',
    'Beorn\'s House',
    'Blue Mountain Dwarf-hold',
    'Bree',
    'Cameth Brin',
    'Carn Dûm',
    'Caves of Ulund',
    'Cirith Ungol',
    'Dancing Spire',
    'Dead Marshes',
    'Dimrill Dale',
    'Dol Amroth',
    'Dol Guldur',
    'Drúadan Forest',
    'Dunharrow',
    'Dunnish Clan-hold',
    'Eagles\' Eyrie',
    'Easterling Camp',
    'Edhellond',
    'Edoras',
    'Ettenmoors',
    'Gladden Fields',
    'Glittering Caves',
    'Goblin-gate',
    'Grey Havens',
    'Henneth Annûn',
    'Himring',
    'Irerock',
    'Iron Hill Dwarf-hold',
    'Isengard',
    'Isles of the Dead that Live',
    'Lake-town',
    'Lond Galen',
    'Lórien ',
    'Lossadan Cairn',
    'Lossadan Camp',
    'Minas Morgul',
    'Minas Tirith',
    'Moria',
    'Mount Doom',
    'Mount Gram',
    'Mount Gundabad',
    'Old Forest',
    'Ost-in-Edhil',
    'Pelargir',
    'Rhosgobel',
    'Rivendell',
    'Ruined Signal Tower',
    'Sarn Goriwing',
    'Shelob\'s Lair',
    'Shrel-Kain',
    'Southron Oasis',
    'Stone-circle',
    'The Lonely Mountain',
    'The Stones',
    'The White Towers',
    'The Wind Throne',
    'Thranduil\'s Halls',
    'Tolfalas',
    'Vale of Erech',
    'Variag Camp',
    'Weathertop',
    'Wellinghall',
    'Woodmen-town',
    'Wose Passage-hold',

    'Fatty Bolger',
    'Neeker-breekers',
];
