const mewh = ['Alatar',
    'Gandalf',
    'Pallando',
    'Radagast',
    'Saruman',
    'Doeth (Durthak)',
    'Euog (Ulzog)',
    'Ill-favoured Fellow',
    'Lugdush',
    'Sly Southerner',
    'Squint-eyed Brute',
    'Uglúk',
    'Keys of Orthanc',
    'Keys to the White Towers',
    'A Merrier World',
    'A New Ringlord',
    'A Strident Spawn',
    'An Untimely Brood',
    'Arcane School',
    'Await the Onset',
    'Bad Company',
    'Blind to All Else',
    'Bow of Alatar',
    'Chambers in the Royal Court',
    'Delver\'s Harvest',
    'Double-dealing',
    'Earth-eater',
    'The Forge-master',
    'The Fortress of Isen',
    'Fortress of the Towers',
    'Friend of Secret Things',
    'Gandalf\'s Friend',
    'Gatherer of Loyalties',
    'Girdle of Radagast',
    'Give Welcome to the Unexpected',
    'Glove of Radagast',
    'Gnawed Ways',
    'The Great Hunt',
    'Great Patron',
    'Great Ruse',
    'Grey Embassy',
    'The Grey Hat',
    'Guarded Haven',
    'Hidden Haven',
    'Huntsman\'s Garb',
    'Join the Hunt',
    'Legacy of Smiths',
    'Man of Skill',
    'Many-coloured Robes',
    'Master of Shapes',
    'Mischief in a Mean Way',
    'Never Refuse',
    'Oromë\'s Warders',
    'Pallando\'s Apprentice',
    'Pallando\'s Hood',
    'Plotting Ruin',
    'Pocketed Robes',
    'Prophet of Doom',
    'Ring of Fire',
    'Saruman\'s Machinery',
    'Saruman\'s Ring',
    'Shameful Deeds',
    'Shifter of Hues',
    'Spells Born of Discord',
    'Squire of the Hunt',
    'Stave of Pallando',
    'Thrall of the Voice',
    'Truths of Doom',
    'War-forges',
    'The White Hand',
    'Winged Change-master',
    'Wizard\'s Myrmidon',
    'Wizard\'s Trove',
    'Greater Half-orcs',
    'Half-orcs',
    'Radagast\'s Black Bird',
    'Promptings of Wisdom',
    'The White Council',
    'The White Wizard',
    'A Panoply of Wings',
    'Beasts of the Wood',
    'Wild Horses',
    'Wild Hounds',
    'Noble Steed',
    'Blasting Fire',
    'Liquid Fire',
    'Mechanical Bow',
    'Vile Fumes',
    'The Black Council',
    'Counterfeit',
    'Crept Along Cleverly',
    'The Fiery Blade',
    'Govern the Storms',
    'Open to the Summons',
    'Piercing All Shadows',
    'Poison of his Voice',
    'Sojourn in Shadows',
    'White Light Broken',
    'Goblin-faces',
    'Blind to the West',
    'Cast from the Order',
    'Cruel Claw Perceived',
    'Echoes of the Song',
    'Flotsam and Jetsam',
    'Fool\'s Bane',
    'Foul Tooth Unsheated',
    'Heart Grown Cold',
    'In the Grip of Ambition',
    'Inner Rot',
    'Ire of the East',
    'Longing for the West',
    'Mask Torn',
    'Nature\'s Revenge',
    'Power Relinquished to Artifice',
    'Rolled down to the Sea',
    'Something Else at Work',
    'Whole Villages Roused',
    'Will You Not Come Down?',
    'Deep Mines',
    'Isengard',
    'Rhosgobel',
    'The White Towers',
]
